<?php

/**
 * @file
 * Google login lets user to login using their google account.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function googlelogin_form_user_login_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  $authentication = \Drupal::service('googlelogin.googlelogin_authentication');
  $url = Url::fromUri($authentication->getAuthenticationtUrl());
  $text = t('Login with your Google account');
  $html_link = \Drupal::l($text, $url);

  $form['googlelogin_text'] = array(
    '#markup' => '<h4 class="label">' . $html_link . '</h4>',
    '#weight' => 100,
  );
}
