<?php

/**
 * @file
 * Google login lets user to login using their google account.
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Implements hook_form_FORM_ID_alter() for Drupal\userForm
 */
function googlelogin_form_user_login_form_alter(&$form, FormStateInterface &$form_state, $form_id){

  $Authentication = \Drupal::service('googlelogin.googlelogin_authentication');
  $link = $Authentication->getAuthenticationtUrl();

  $form['googlelogin_text'] = array(
    '#markup' => '<h4 class="label"> Google Link</h4>',
    '#weight' => 100,
  );
}
